#pragma config(Sensor, in1,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in2,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderMogo,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  limitLeft,      sensorTouch)
#pragma config(Sensor, dgtl8,  limitRight,     sensorTouch)
#pragma config(Motor,  port2,           backR,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backL,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           tipR,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           tipL,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           frontL,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           frontR,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


int front = 1;
int back  = -1;
int right = 1;
int left = -1;

int kpL = 0;
int kiL = 0;
int kdL = 0;

int kpR = 0;
int kiR = 0;
int kdR = 0;

int MAX_POWER = 121;
int MIN_POWER = 40;
int MAX_ERROR = 50;

int constant = 1;

float distanceMogo1 = (48/circumference) * 360; //Distance for the first mogo
float distanceTest = (10/circumference) * 360;

int timeMogoIntake = 61; //number of ticks for the mobo intake to go down
int g = 0;


void move(float targetDistance, int power)
{
	/* Variables used to calculate how fast bot is moving*/
	float wheelDiameter = 4.5;
	float circumference = wheelDiameter * PI; //Roughly 14.13 inches
	float currentDistance = 0;
	float errorR = 1;
	float errorL = 1;
	float lastErrorL = 0;
	float lastErrorR = 0;
	float integralL = 0;
	float derivativeL = 0;
	float integralR = 0;
	float derivativeR = 0;
	int powerLeft = 0;
	int powerRight = 0;

	while(errorL > 0 && errorR > 0)
	{
		currentDistanceL = SensorValue[encoderLeft] / 360 * circumference;
		currentDistanceR = SensorValue[encoderRight] / 360 * circumference;

		errorL = targetDistance - currentDistance;
		errorR = targetDistance - currentDistance;

		integralL = (errorL > MAX_ERROR / kiL) ? 0 : (integralL + errorR);
		derivativeL = errorL - lastErrorL;
		
		integralR = (errorR > MAX_ERROR / kiR) ? 0 : (integralR + errorR);
		derivativeR = errorR - lastErrorR;


		powerL = (errorL * kpL) + (integralL * kiL) + (derivativeL * kdL);
		powerR = (errorR * kpR) + (integralR * kiR) + (derivativeR * kdR);

		if(power > 0)
		{
			if(power > MAX_POWER)
			{
				power = MAX_POWER;
			}
			else if(power < MIN_POWER)
			{
				power = MIN_POWER;
			}
		}
		else if(power < 0)
		{
			if(power < -MAX_POWER)
			{
				power = -MAX_POWER;
			}
			else if(power > -MIN_POWER)
			{
				power = -MIN_POWER;
			}
		}
		powerLeft = encoderPID(power);
		powerRight = encoderPID(power);
		
		motor[frontL] = powerLeft;
		motor[backL] = powerLeft;
		motor[frontR] = powerRight;
		motor[backR] = powerRight;

		lastError = error;
	}
	resetDrive();
}

int encoderPID(int power, int side)
{
	int master = 0;
	int slave = 0;
	int error = 1;
	int kp = 0;
	
	master = (SensorValue[encoderRight] >= SensorValue[encoderLeft]) ? SensorValue[encoderRight] : SensorValue[encoderLeft];
	slave = (SensorValue[encoderRight] >= SensorValue[encoderLeft]) ? SensorValue[encoderLeft] : SensorValue[encoderRight];
	
	error = master - slave;
	if(side == right)
	{
		if(SensorValue[encoderRight] >= SensorValue[encoderLeft])
		{
			power = power - error * kp; 
		}
	}
	else if(side == left)
	{
		if(SensorValue[encoderRight] < SensorValue[encoderLeft])
		{
			power = power +
		}
	}
	power = (side == right && SensorValue[encoderRight] >= SensorValue[encoderLeft]) ? power +  : power;
	
	return power;
}
